export default {

	defaultLanguageKeys: {
	
		"Język": "Język",
		"Ilość" : "Ilość",
		"DODAJ STEROWANIE": "DODAJ STEROWANIE",
		"Zmiana języka": "Zmiana języka",
		"Szerokość":"Szerokość",
		"Produkt":"Produkt",
		"Wysokość":"Wysokość",
		"Skrzynka":"Skrzynka",
		"Cena bazowa systemu":"Cena bazowa systemu",
		"Kolor":"Kolor",
		"Waluta":"Waluta",
	 	"Razem netto":"Razem netto",
		"Cena netto":"Cena netto",
		"Rabat":"Rabat",
		"Kwota rabatu":"Kwota rabatu",
		"Cena po rabacie":"Cena po rabacie",
		"Suma VAT":"Suma Vat",
		"Brutto":"Brutto",
		"Podatek VAT":"Podatek VAT",
		"Montaż":"Montaż",
		"Pilot 1-kanałowy ręczny":"Pilot 1-kanałowy ręczny",
		"Opis oferty":"Opis oferty",
		"DODAJ POZYCJĘ":"DODAJ POZYCJĘ",
		"MONTAŻ":"MONTAŻ",
		"WYBIERZ KATEGORIĘ/ EDYTUJ POZYCJE Z KATEGORII":"WYBIERZ KATEGORIĘ/ EDYTUJ POZYCJE Z KATEGORII",
		"Klienci":"Klienci",
		"ZAPISZ SZCZEGÓŁY OFERTY":"ZAPISZ SZCZEGÓŁY OFERTY",
		"Warunki płatności":"Warunki płatności",
		"Wróć do ofert":"Wróć do ofert",
		"Zapisane dane oferty z dnia":"Zapisane dane oferty z dnia",
		"Suma netto po rabacie":"Suma netto po rabacie",
		"Suma podatku":"Suma podatku",
		"Do zapłaty brutto":"Do zapłaty brutto",
		"Waluta dokumentu":"Waluta dokumenu",
		"Numer konta bankowego":"Numer konta bankowego",
		"Wymagana kwota zadatku":"Wymagana kwota zaadatku",
		"Data ważności oferty":"Data ważności oferty",
		"Wyloguj":"Wyloguj",
		"Oferta":"Oferta",
		"Podatek VAT":"Podatek VAT",
		"Narzut":"Narzut",
		"Rabat":"Rabat",
		"KURS EURO":"KURS EURO",
		"Opis oferty":"Opis oferty",
		"Wymagany":"Wymagany",
		"zadatek":"zadatek",
		"Sugerowany":"Sugerowany",
		"Kwota wymaganego zadatku":"Kwota wymaganego zadatku",
		"Ważność oferty":"Ważność oferty",
		"Dni":"Dni",
	
	
				
	},
	languageOptions: [
		"Polski",
		"Deutch",
		"English"
	]
}